arb-dir: lib/l10n
template-arb-file: app_ko.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/generated/l10n
nullable-getter: false
synthetic-package: false
use-deferred-loading: false
required-resource-attributes: false
use-escaping: false
suppress-warnings: false 